<?php
namespace lib\RealmContext;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-04 at 01:45:07.
 */
class RealmManagerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var RealmManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RealmManager;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    function executeScriptDataProvider()
    {
        $datasets = [
            [[
                'result' => "1 3 N\n5 1 E\n",
                'dataFeed' => [ "5 5",
                            "1 2 N",
                            "LMLMLMLMM",
                            "3 3 E",
                            "MMRMMRMRRM"
                ]
            ]],
            [[
                'result' => "1 1 W\n0 3 W\n5 2 E\n1 2 N\n3 0 E\n",
                'dataFeed' => [
                    "5 5",
                    "1 1 N",
                    "MMMRMMMRMMMRMMM",
                    "0 3 S",
                    "MMMLMMMMMLMMMLMMMMM",
                    "5 4 S",
                    "MMLMMMMM",
                    "1 5 S",
                    "MMMMMRLLL",
                    "3 5 N",
                    "RRMRMLMLMMRMRMMLMLMMRMRMRR"
                ]
            ]]
        ];

        return $datasets;
    }

    /**
     * @covers lib\RealmContext\RealmManager::executeScript
     * @dataProvider executeScriptDataProvider
     */
    public function testExecuteScript($dataset)
    {
        $actual = $this->object->executeScript($dataset['dataFeed']);
        $this->assertSame($dataset['result'], $actual);
    }
}
