<?php
namespace lib\LandscapeContext;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-02 at 13:21:36.
 */
class Landscape2DPointTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Landscape2DPoint
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Landscape2DPoint([0,1,6,7]);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }


    protected function setPositionProvider()
    {
        $datasets = [

        ];

        return $datasets;
    }

    /**
     * @param array $dataset
     * @dataProvider setPositionProvider
     */
    protected function testSetPosition($dataset)
    {
        $this->markTestIncomplete('Not implemented.');
    }
}
