<?php
namespace lib\LandscapeContext;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-01 at 23:07:09.
 */
class Landscape2DPointTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Landscape2DPoint
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Landscape2DPoint();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers lib\LandscapeContext\Landscape2DPoint::isValidBoundaries
     * @todo   Implement testIsValidBoundaries().
     */
    public function testIsValidBoundaries()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers lib\LandscapeContext\Landscape2DPoint::isValidCoordinates
     * @todo   Implement testIsValidCoordinates().
     */
    public function testIsValidCoordinates()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
