<?php
namespace lib\Enum;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-01 at 20:24:19.
 */
class CardinalDirectionTest extends \PHPUnit_Framework_TestCase
{
    const CD = 'N';
    /**
     * @var CardinalDirection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CardinalDirection(static::CD);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testGet()
    {
        $actual = $this->object->get();
        $this->assertSame(static::CD, $actual);
    }

    public function testToString()
    {
        $actual = $this->object . '';
        $this->assertSame(static::CD, $actual);
    }

    public function testAsArray()
    {
        $actual = CardinalDirection::asArray();
        $this->assertArrayHasKey(static::CD, $actual);
    }
}
