<?php
namespace lib\Enum;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-02 at 19:58:29.
 */
class EnumTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Enum
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $this->object = new Enum;
        $this->object = $this->getMock(Enum::class, [], ['N']);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers lib\Enum\Enum::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers lib\Enum\Enum::get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers lib\Enum\Enum::asArray
     * @todo   Implement testAsArray().
     */
    public function testAsArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers lib\Enum\Enum::getPrev
     * @todo   Implement testGetPrev().
     */
    public function testGetPrev()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers lib\Enum\Enum::getNext
     * @todo   Implement testGetNext().
     */
    public function testGetNext()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
